apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
    app: whisper-bot

  name: whisper-bot

spec:
  selector:
    matchLabels:
      app: whisper-bot

  template:
    metadata:
      labels:
        app: whisper-bot

    spec:
      containers:
        - image: ghcr.io/wgbh-mla/whisper-bot:latest
          name: whisper-bot
          imagePullPolicy: Always
          command: ['/bin/bash', '-c']
          args: ['sleep 6000']
          volumeMounts:
            - mountPath: '/m'
              name: media
            - mountPath: '/root/.cache/whisper'
              name: models
          resources:
            limits:
              cpu: '2'
              memory: '4Gi'
              nvidia.com/gpu: '1'
            requests:
              cpu: '1000m'
              memory: '1000Mi'
              nvidia.com/gpu: '1'
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
        - name: models
          persistentVolumeClaim:
            claimName: whisper-models
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: render
                    operator: In
                    values:
                      - gpu
      tolerations:
        - key: gpu
          operator: Exists
          effect: NoSchedule
