apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-app-swt-detection-v3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-swt-detection-v3
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
