apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
    app: {{ cookiecutter.app_name }}

  name: {{ cookiecutter.app_name }}

spec:
  selector:
    matchLabels:
      app: {{ cookiecutter.app_name }}

  template:
    metadata:
      labels:
        app: {{ cookiecutter.app_name }}

    spec:
      containers:
        - image: {{ cookiecutter.app_image }}
          name: {{ cookiecutter.app_name }}
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: '/m'
              name: media
          resources:
            limits:
              cpu: '{{ cookiecutter.cpu_limit }}'
              memory: '{{ cookiecutter.memory_limit }}'
            requests:
              cpu: '100m'
              memory: '100Mi'
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: render
                    operator: In
                    values:
                      - cpu
