apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-{{ cookiecutter.app_name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ cookiecutter.app_name }}
  minReplicas: 1
  maxReplicas: {{ cookiecutter.maxReplicas }}
  targetCPUUtilizationPercentage: {{ cookiecutter.targetCPUUtilizationPercentage }}
