apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
    app: app-east-textdetection

  name: app-east-textdetection

spec:
  selector:
    matchLabels:
      app: app-east-textdetection

  template:
    metadata:
      labels:
        app: app-east-textdetection

    spec:
      containers:
        - image: ghcr.io/clamsproject/app-east-textdetection:latest
          name: app-east-textdetection
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: '/m'
              name: media
          resources:
            limits:
              cpu: '2'
              memory: '2Gi'
            requests:
              cpu: '200m'
              memory: '100Mi'
      volumes:
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: render
                    operator: In
                    values:
                      - cpu
