apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-app-barsdetection
spec:
  scaleTargetRef:
    kind: ReplicaSet
    name: app-barsdetection
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
